# CHANGE THIS

url: "https://www.edwinlock.com"

fullname: Edwin Lock
position: Lecturer in Computer Science
department: Department of Informatics
university: King's College London

building: "Strand"  # optional
street: "" # optional
city: "London" # optional
postcode: "WC2R 2LS"  # optional
country: "United Kingdom"  # optional

email: mail@edwinlock.com
secondary: edwin.lock@kcl.ac.uk  # optional

formurl: https://formspree.io/xzbjkqje

# DON'T CHANGE THIS
collections:
  publications:
  preprints:
