# Change this
fullname: Edwin Lock
position: Doctoral Candidate
department: Department of Computer Science
university: University of Oxford

# Don't change this
collections:
  publications:
  preprints:
