# CHANGE THIS

url: "https://www.edwinlock.com"

fullname: Edwin Lock
position: Research Fellow
department: Nuffield College
university: University of Oxford

building: Nuffield College  # optional
street: New Road  # optional
city: Oxford  # optional
postcode: OX1 1NF  # optional
country: United Kingdom  # optional

email: mail@edwinlock.com
secondary: edwin.lock@economics.ox.ac.uk  # optional

formurl: https://formspree.io/xzbjkqje

# DON'T CHANGE THIS
collections:
  publications:
  preprints:
